/**
 * Generated by scripts/write-version.mjs from the version in package.json.
 * Committed so a fresh clone compiles and so a release is visible in the diff.
 * Do not edit by hand - run "npm version <bump>".
 */
export const APP_VERSION = '1.1.2';
