/**
 * Generated by scripts/finalize-wasm-build.mjs during "npm run build:wasm".
 * Committed so a fresh clone compiles before anyone has run a .NET build.
 * Do not edit by hand.
 */
export const DOTNET_BUILD_INFO = {
  sdkVersion: '10.0.302',
  targetFramework: 'net10.0',
} as const;
