name: Feature Request
description: Suggest a new feature or enhancement for the toolbox
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe the feature and provide examples if possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added.
      placeholder: Tell us about the feature you want
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: |
        If possible, provide examples of how the feature would behave or be used.
        You can include:
        - Screenshots or mockups
        - Code examples
        - Use cases
        - Links to similar features in other tools
      placeholder: |
        Example 1:
        When I input X, the tool should output Y...
        
        Example 2:
        Similar to how Tool Z handles this feature...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional information that might be helpful
    validations:
      required: false
