import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const PACKAGE_JSON = 'package.json';
const VERSION_FILE = join('src', 'environments', 'app-version.ts');

const check = process.argv.includes('--check');

const { version } = JSON.parse(readFileSync(PACKAGE_JSON, 'utf8'));

if (typeof version !== 'string' || !version) {
  console.error(`\n[version] "version" is missing from ${PACKAGE_JSON}.\n`);
  process.exit(1);
}

const contents = `/**
 * Generated by scripts/write-version.mjs from the version in package.json.
 * Committed so a fresh clone compiles and so a release is visible in the diff.
 * Do not edit by hand - run "npm version <bump>".
 */
export const APP_VERSION = '${version}';
`;

const previous = existsSync(VERSION_FILE) ? readFileSync(VERSION_FILE, 'utf8') : null;

if (previous === contents) {
  process.exit(0);
}

if (check) {
  console.error(
    `\n[version] ${VERSION_FILE} does not match package.json (${version}).` +
      `\n[version] Run "node scripts/write-version.mjs" and commit the result.\n`
  );
  process.exit(1);
}

writeFileSync(VERSION_FILE, contents);
console.log(`[version] app version set to ${version}`);
